apex: true
wandb: false
competition: HOA3D
backbone: resnet18d
max_grad_norm: 1000
debug: false
debug_train_size: 200
scheduler: cosine
num_warmup_steps: 0
epochs: 2
decoder_lr: 0.005
betas: !!python/tuple
- 0.9
- 0.999
batch_size: 4
infer_batch_size: 4
ckpt_name: unet3d-baseline
weight_decay: 0.1
seed: 42
print_freq: 50
eval_freq: 1000
eval_step_save_start_epoch: 0
train: true